// Capital cities keyed by ISO 3166-1 alpha-3 code (matches the codes the
// game assigns to each country). Antarctica is intentionally absent — the
// "Guess Capital" option simply won't appear for countries with no entry.
window.CAPITALS = {
    AFG: "Kabul", AGO: "Luanda", ALB: "Tirana", ARE: "Abu Dhabi",
    ARG: "Buenos Aires", ARM: "Yerevan", AUS: "Canberra", AUT: "Vienna",
    AZE: "Baku", BDI: "Gitega", BEL: "Brussels", BEN: "Porto-Novo",
    BFA: "Ouagadougou", BGD: "Dhaka", BGR: "Sofia", BHS: "Nassau",
    BIH: "Sarajevo", BLR: "Minsk", BLZ: "Belmopan", BOL: "Sucre",
    BRA: "Brasília", BRN: "Bandar Seri Begawan", BTN: "Thimphu", BWA: "Gaborone",
    CAF: "Bangui", CAN: "Ottawa", CHE: "Bern", CHL: "Santiago",
    CHN: "Beijing", CIV: "Yamoussoukro", CMR: "Yaoundé", COD: "Kinshasa",
    COG: "Brazzaville", COL: "Bogotá", CRI: "San José", CUB: "Havana",
    CYP: "Nicosia", CZE: "Prague", DEU: "Berlin", DJI: "Djibouti",
    DNK: "Copenhagen", DOM: "Santo Domingo", DZA: "Algiers", ECU: "Quito",
    EGY: "Cairo", ERI: "Asmara", ESH: "El Aaiún", ESP: "Madrid",
    EST: "Tallinn", ETH: "Addis Ababa", FIN: "Helsinki", FJI: "Suva",
    FLK: "Stanley", FRA: "Paris", GAB: "Libreville", GBR: "London",
    GEO: "Tbilisi", GHA: "Accra", GIN: "Conakry", GMB: "Banjul",
    GNB: "Bissau", GNQ: "Malabo", GRC: "Athens", GRL: "Nuuk",
    GTM: "Guatemala City", GUY: "Georgetown", HND: "Tegucigalpa", HRV: "Zagreb",
    HTI: "Port-au-Prince", HUN: "Budapest", IDN: "Jakarta", IND: "New Delhi",
    IRL: "Dublin", IRN: "Tehran", IRQ: "Baghdad", ISL: "Reykjavik",
    ISR: "Jerusalem", ITA: "Rome", JAM: "Kingston", JOR: "Amman",
    JPN: "Tokyo", KAZ: "Astana", KEN: "Nairobi", KGZ: "Bishkek",
    KHM: "Phnom Penh", KOR: "Seoul", KOS: "Pristina", KWT: "Kuwait City",
    LAO: "Vientiane", LBN: "Beirut", LBR: "Monrovia", LBY: "Tripoli",
    LKA: "Colombo", LSO: "Maseru", LTU: "Vilnius", LUX: "Luxembourg",
    LVA: "Riga", MAR: "Rabat", MDA: "Chișinău", MDG: "Antananarivo",
    MEX: "Mexico City", MKD: "Skopje", MLI: "Bamako", MMR: "Naypyidaw",
    MNE: "Podgorica", MNG: "Ulaanbaatar", MOZ: "Maputo", MRT: "Nouakchott",
    MWI: "Lilongwe", MYS: "Kuala Lumpur", NAM: "Windhoek", NCL: "Nouméa",
    NER: "Niamey", NGA: "Abuja", NIC: "Managua", NLD: "Amsterdam",
    NOR: "Oslo", NPL: "Kathmandu", NZL: "Wellington", OMN: "Muscat",
    PAK: "Islamabad", PAN: "Panama City", PER: "Lima", PHL: "Manila",
    PNG: "Port Moresby", POL: "Warsaw", PRI: "San Juan", PRK: "Pyongyang",
    PRT: "Lisbon", PRY: "Asunción", PSE: "Ramallah", QAT: "Doha",
    ROU: "Bucharest", RUS: "Moscow", RWA: "Kigali", SAU: "Riyadh",
    SDN: "Khartoum", SEN: "Dakar", SLB: "Honiara", SLE: "Freetown",
    SLV: "San Salvador", SOM: "Mogadishu", SRB: "Belgrade", SSD: "Juba",
    SUR: "Paramaribo", SVK: "Bratislava", SVN: "Ljubljana", SWE: "Stockholm",
    SWZ: "Mbabane", SYR: "Damascus", TCD: "N'Djamena", TGO: "Lomé",
    THA: "Bangkok", TJK: "Dushanbe", TKM: "Ashgabat", TLS: "Dili",
    TTO: "Port of Spain", TUN: "Tunis", TUR: "Ankara", TWN: "Taipei",
    TZA: "Dodoma", UGA: "Kampala", UKR: "Kyiv", URY: "Montevideo",
    USA: "Washington, D.C.", UZB: "Tashkent", VEN: "Caracas", VNM: "Hanoi",
    VUT: "Port Vila", YEM: "Sana'a", ZAF: "Pretoria", ZMB: "Lusaka",
    ZWE: "Harare"
};
